apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../platform/namespaces/base
  - ../../platform/ingress/overlays/dev
  - ../../platform/logging/overlays/dev
  - ../../platform/monitoring/overlays/dev
  - ../../platform/OTel/overlays/dev
  - ../../workloads/demo-app/overlays/dev
  - ingress-nginx.yaml
  - root-app.yaml
  - demo-app.yaml
  - monitoring.yaml
  - logging.yaml
 