apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../platform/namespaces/base
  - ../../platform/ingress/overlays/prod
  - ../../platform/logging/overlays/prod
  - ../../platform/monitoring/overlays/prod
  - ../../platform/OTel/overlays/prod
  - ../../workloads/demo-app/overlays/prod
